### ISSUE TITLE
Feature Request: Add number at the end of slug if entry isn't unique

### ISSUE THREAD

**Issue by dwainetrain** [pauloamgomes/contentful-better-slugs#7]
Similar to how Wordpress will just create a "hello-world-1" if "hello-world" already exists. Do you think this would be possible.

My use case is that I have many artists with artworks with the same title, so I get "artist/necklace" then if they have another necklace I need to add a number at the end to differentiate it. Though I don't know what the number is, it would be better if it was just automatically generated based on the existing slug names.

**Comment by pauloamgomes** [comment]
Hi @dwainetrain , thanks for flagging, I'll check

**Comment by pauloamgomes** [comment]
Thanks @dwainetrain , but I don't plan to implement this feature as is not straightforward to do and will not scale properly, in other systems like wordpress its a bit different because you access directly the BD, here it's required to leverage the API to get all entries that start with the slug and extract the last numeric value after the last "-", that would result in a bit messy implementation. Happy to review a PR if you find a better solution.
